### ISSUE TITLE
remove breadcrumbs in login form

### ISSUE THREAD

**Issue by ghost** [gbdlin/django-admin-toolbox#4]
problem: breadcrumbs in login form
reason:
templates/admin/base.html
line 59：{#        {% if True|check_show_breadcrumbs %} #}
line 68：{#        {% endif %} #}
solution: remove {# and #}

**Comment by gbdlin** [comment]
Can you please explain more how to fix that or just create PR for that fix?

**Comment by gbdlin** [comment]
Okay, I've managed to recreate this problem. It is now fixed.
